:py:mod:`relevanceai.errors`
============================

.. py:module:: relevanceai.errors

.. autoapi-nested-parse::

   Missing field error



Module Contents
---------------

.. py:exception:: RelevanceAIError

   Bases: :py:obj:`Exception`

   base class for all errors



.. py:exception:: MissingFieldError

   Bases: :py:obj:`RelevanceAIError`

   Error handling for missing fields


.. py:exception:: APIError

   Bases: :py:obj:`RelevanceAIError`

   Error related to API


.. py:exception:: ClusteringResultsAlreadyExistsError

   Bases: :py:obj:`RelevanceAIError`

   Error is raised when the clustering dataset already exists



